name: Publish Dotnet Package (NuGet)

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build and Create the package
      run: dotnet build SteamCMD.ConPTY -c Release

    - name: Publish the package to nuget.org
      run: dotnet nuget push SteamCMD.ConPTY\bin\Release\*.nupkg -s "https://api.nuget.org/v3/index.json" -k "$NUGET_AUTH_TOKEN" 
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
