name: Dotnet Publish WPF

on:
  push:
    tags:
      - '*'

jobs:
  draft:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Publish SteamCMD.WPF
      run: dotnet publish SteamCMD.WPF -c Release -o Publish

    - name: Draft - steamcmd.wpf.exe
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: Publish/steamcmd.wpf.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
